spring.application.name=profile-gateway
server.port=8084

services.profile-service.url=${PROFILE_SERVICE_URL:http://localhost:8081}
services.venue-service.url=${VENUE_SERVICE_URL:http://localhost:8082}
services.image-service.url=${IMAGE_SERVICE_URL:http://localhost:8083}
