spring.application.name=venue-service
server.port=8082

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/venue}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:rootpass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.flyway.enabled=true
