### Get all profiles
GET http://localhost:8080/profiles
Accept: application/json

### Get a single profile by id
GET http://localhost:8080/profile/1
Accept: application/json

### Get all venues connected to a profile
GET http://localhost:8080/profile/1/venues
Accept: application/json

### Create a profile
POST http://localhost:8080/profile/create
Content-Type: application/json

{
  "name": "Frida5",
  "email": "frida@art.com",
  "profileNotes": "Painter exploring identity and nature"
}

### Get all venues
GET http://localhost:8080/venues
Accept: application/json

### Get a single venue by id
GET http://localhost:8080/venue/1
Accept: application/json

### Create a venue
POST http://localhost:8080/venue/create
Content-Type: application/json

{
  "name": "The Art House",
  "location": "123 Main St, Art City",
  "capacity": 200,
  "venueNotes": "laid-back staff"
}

### Create an artist's venue
POST http://localhost:8080/profile/venue/create
Content-Type: application/json

{
  "profileId": 2,
  "venueId": 2,
  "interactionNotes": "They might consider me"
}



### Create a venue's artist
POST http://localhost:8080/profile/venue/create
Content-Type: application/json

{
  "venueId": 2,
  "profileId": 2,
  "interactionNotes": "We got this cold call from this artist again"
}

